---
Name: geonetconfig
---
Catalogue:
  'metadata_standard': 'iso'

  'spamprotection_enabled': false

  'search_form': 'CatalogueSearchForm'

  'cssfile': 'geocatalogue/css/cataloguepage.css'

  'site_status': 'setup'

  'automatic_publishing': false

  standard_definitions:
    iso:
      'name': 'ISO19139'
      'request': 'cswGetRecordsSummaryISO_xml'
      'response': 'ParseXML2Summary',
      'full_response': 'ParseXML2ANZLIC'

    anzlic:
      'name': 'ANZLIC Metadata Profile'
      'request': 'cswGetRecordsSummaryISO_xml'
      'response': 'ParseXML2Summary',
      'full_response': 'ParseXML2ANZLIC'

    mcp:
      'name': 'Australian Marine Community Profile MCP'
      'request': 'cswGetRecordsSummaryISO_xml'
      'response':      'ParseXML2Summary'
      'full_response': 'ParseXML2MCP'

  geonetwork:

    api_version: 'geonetwork_v2_10'

    default:
      csw_url: 'srv/en/csw'
      geonetwork_url: 'srv/en/xml.metadata'

    geonetwork_v2_10:
      csw_url: 'srv/eng/csw'
      geonetwork_url: 'srv/eng/xml.metadata'
