---
Name: geonetconfig
---
Catalogue:
  'metadata_standard': 'iso'

  'spamprotection_enabled': false

  'search_form': 'CatalogueSearchForm'

  'cssfile': 'geocatalogue/css/cataloguepage.css'

  'site_status': 'setup'

  # Email_sender used for all emails send out by the catalogue module as a sender. This includes
  # Confirmation emails to the website user who registers new records and notifications to the maintainer
  # of the website.
  'email_sender': ''

  standard_definitions:
    iso:
      'name': 'ISO19139'
      'request': 'cswGetRecordsSummaryISO_xml'
      'response': 'ParseXML2Summary',
      'full_response': 'ParseXML2ANZLIC'

    anzlic:
      'name': 'ANZLIC Metadata Profile'
      'request': 'cswGetRecordsSummaryISO_xml'
      'response': 'ParseXML2Summary',
      'full_response': 'ParseXML2ANZLIC'

    mcp:
      'name': 'Australian Marine Community Profile MCP'
      'request': 'cswGetRecordsSummaryISO_xml'
      'response':      'ParseXML2Summary'
      'full_response': 'ParseXML2MCP'

  geonetwork:

    api_version: 'geonetwork_v2_10'

    default:
      csw_url: 'srv/en/csw'
      geonetwork_url: 'srv/en/xml.metadata'
      url_publish: 'srv/en/xml.metadata.privileges' # see GnPublishMetadataCommand
      url_getuuid: 'srv/en/xml.metadata.get' # GnGetUUIDOfRecordByIDCommand

    geonetwork_v2_10:
      csw_url: 'srv/eng/csw'
      geonetwork_url: 'srv/eng/xml.metadata'
      url_publish: 'srv/eng/metadata.admin' # see GnPublishMetadata_v2_10Command
