---
Name: geonetconfig
---
Catalogue:
  'spamprotection_enabled': false

  'metadata_standard': 'iso'

  'search_form': 'CatalogueSearchForm'

  'cssfile': 'geocatalogue/css/cataloguepage.css'

  'site_status': 'setup'

  standard_definitions:
    iso:
      'name': 'ISO19139'
      'request': 'cswGetRecordsSummaryISO_xml'
      'response': 'ParseXML2Summary',
      'full_response': 'ParseXML2ANZLIC'

    anzlic:
      'name': 'ANZLIC Metadata Profile'
      'request': 'cswGetRecordsSummaryISO_xml'
      'response': 'ParseXML2Summary',
      'full_response': 'ParseXML2ANZLIC'
      'response_old': '../geocatalogue/xslt/ISO19139/iso19139_to_silverstripe.xsl'

    dublin:
      'name': 'Dublin Core'
      'request': 'cswGetRecordsSummaryDC_xml'
      'response': '../geocatalogue/xslt/DublicCore/dubliccore_to_silverstripe.xsl'

    mcp:
      'name': 'Australian Marine Community Profile MCP'
      'request': 'cswGetRecordsSummaryISO_xml'
      'response':      'ParseXML2Summary'
      'full_response': 'ParseXML2MCP'
